# Управляемая самостоятельная работа 1

# Функции в Pyhon. Инструменты функционального программирования

Фамилия Имя Студента, апрель 2025

При выполнении заданий можно пользоваться только справочной системой Python, доступной через меню **Help | Python Reference**. Для получения информации об объектах можно использовать функцию `help` и команду JupyterLab `?`

## Задание 1. Функция суммирования (3 балла)

Напишите пользовательскую функцию `func1` с произвольным количеством позиционных и ключевых аргументов одного типа (числовые типы, строки, кортежи, списки), которая возвращает результат применения операции сложения ко всем аргументам функции. При вызове функции без аргументов она должны возвращать `None`.

Приведите следующие тесты вызова функции `func1`:
- без аргументов,
- 40 позиционных аргументов числового типа,
- 40 ключевых аргументов строкового типа,
- по 20 позиционных и ключевых аргументов спискового типа.

## Задание 2. Вычисления со списками и массивами (2 балла)

### Задание 2.1

Постройте список `x` со значениями, равномерно распределенными на отрезке $[a,b]$ с шагом $step$, где $a=0$, $b=2$, $step=0.1$.

Вычислите значения $y = \sin^2(x) + ln(1 + 3 x)$ по значениям из списка `x` тремя способами:
- с использованием включения (питоновский стиль),
- с использованием цикла (процедурный стиль),
- с использованием функции `map` (функциональный стиль).

Результирующая переменная `y` при реализации каждым из способов должна ссылаться на списковый объект, содержащий только те значения функции, которые меньше 2

In [24]:
a=0
import math
b=2
step=0.1
s_list = [a + i*step for i in range(int(b/0.1))]
y = [math.sin(xi)**2 + math.log(1 + 3 * xi) for xi in s_list if math.sin(xi)**2 + math.log(1 + 3 * xi) < 2]
result=[]
for xi in s_list:
    val = math.sin(xi)**2 + math.log(1 + 3 * xi)
    if val < 2:
       result.append(val)
spisok=list(filter(lambda val: val < 2, map(lambda xi: math.sin(xi)**2 + math.log(1 + 3 * xi), s_list)))
spisok

[0.0,
 0.27233097554687025,
 0.5094731322442931,
 0.7291860787175557,
 0.9401040056906875,
 1.1461395789400852,
 1.3484405399428216,
 1.5464185400409802,
 1.7383751927727604,
 1.9219338669967225]

### Задание 2.2

Постройте массив `x` со значениями, равномерно распределенными на отрезке $[a,b]$ с шагом $step$, где $a=0$, $b=2$, $step=0.1$.


Вычислите значения $y = \ min(sin^2(x) + ln(1 + 3 x), 2)$ по значениям из массива `x`, не используя включения, циклы и функцию `map`. Переменная `y` должна быть массивом. Объедините массивы `x` и `y` в матрицу из двух столбцов.  

In [35]:
import numpy as np
a = 0
b = 2
step = 0.1
x = np.arange(a, b + step, step)
y = np.minimum(np.sin(x)**2 + np.log(1 + 3 * x), 2)

xy = np.array(list(zip(x, y)))
list(zip([2],[3]))

[(2, 3)]

## Задание 3. Генераторная функция и функция reduce (2 балла)

### Задание 3.1

Напишите генераторную функцию `func3` для генерации нечетных членов арифметической прогрессии $a_1 = 1$, $a_{n+1} =  a_n + 1$, $n=1, 2, \ldots$.

На основе генераторной функции создайте список из 9 первых членов африметической прогрессии.

In [41]:
def gen():
    a=1
    b=1
    while True:
        yield a
        a+=b
l=gen()
for x in range(9):
    print(next(l))

1
2
3
4
5
6
7
8
9


### Задание 3.2

Вычислите 9-ый член арифметической прогрессии с помощью функции `reduce` из модуля `functools`. Функцию `func3` использовать не нужно.

In [5]:
import functools
functools.reduce(lambda x,l:x+1,range(8),1)

9

## Задание 4. Фабричная функция, функция-замыкание (1.5 балла)

Напишите фабричную функцию `func4`, которая содержит локальную переменную `x`, ссылающуюся на числовый объект. Функция-замыкание, которую возвращает фабричная функция, должна увеличивать на один значение переменной `x` из локальной области видимости фабричной функции и возвращать измененное значение в качестве результата с использованием f-строки.

Создайте функцию-замыкание и вызовите ее три раза. Объясните в текстовой ячейке результаты последовательных вызовов функции-замыкания.

In [12]:
def zam(x):
    n=x
    def vn():
        nonlocal n
        n+=1
        return f"{n}"
    return vn
vyzov=zam(8)
for i in range(3):
    print(vyzov())

9
10
11


## Задание 5. Декорирование функции (1.5 балла)

Напишите функцию декоратор `func5` для функции с произвольным количеством позиционных и ключевых аргументов. Декоратор должен измерять и выводить время выполнения декорируемой функции.
Примените декоратор `func5` к пользовательской функции из Задания 1, используя синтаксис `@func5`, и вызовите эту функцию с различными аргументами.

КОНТРОЛЬНЫЕ ВОПРОСЫ

In [4]:
import numpy as np

In [6]:
x=np.linspace(0,1,100)
x

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [26]:
y=lambda x:x+2

In [28]:
l=y(x)

In [30]:
np.transpose(np.array([x,l]))

array([[0.        , 2.        ],
       [0.01010101, 2.01010101],
       [0.02020202, 2.02020202],
       [0.03030303, 2.03030303],
       [0.04040404, 2.04040404],
       [0.05050505, 2.05050505],
       [0.06060606, 2.06060606],
       [0.07070707, 2.07070707],
       [0.08080808, 2.08080808],
       [0.09090909, 2.09090909],
       [0.1010101 , 2.1010101 ],
       [0.11111111, 2.11111111],
       [0.12121212, 2.12121212],
       [0.13131313, 2.13131313],
       [0.14141414, 2.14141414],
       [0.15151515, 2.15151515],
       [0.16161616, 2.16161616],
       [0.17171717, 2.17171717],
       [0.18181818, 2.18181818],
       [0.19191919, 2.19191919],
       [0.2020202 , 2.2020202 ],
       [0.21212121, 2.21212121],
       [0.22222222, 2.22222222],
       [0.23232323, 2.23232323],
       [0.24242424, 2.24242424],
       [0.25252525, 2.25252525],
       [0.26262626, 2.26262626],
       [0.27272727, 2.27272727],
       [0.28282828, 2.28282828],
       [0.29292929, 2.29292929],
       [0.

In [ ]:
x_coord = list(line1.get_xdata())
 y_coord = list(line1.get_ydata())

 x_coord.append(point[0])
 y_coord.append(point[1])

In [ ]:
x=list(line.get_xdata())
y=list(line.get_ydata())

In [4]:
import numpy as np

In [8]:
R=8
t=np.arange(0,2*np.pi,2*np.pi/5)

In [12]:
ver=[0,0]+R*np.transpose([np.cos(t),np.sin(t)])
ver

array([[ 8.        ,  0.        ],
       [ 2.47213595,  7.60845213],
       [-6.47213595,  4.70228202],
       [-6.47213595, -4.70228202],
       [ 2.47213595, -7.60845213]])

In [ ]:
side=[ver[i]+R*np.transpose([np.cos(angle+np.pi +i*alpha),)

In [17]:
from time import time
def funcOut(func,max_calls,period):
    fr=0
    def wrapper(*args, **kwargs):
        fr+=1
        start = time()
        func(*args, **kwargs)
        end = time()
        period_func=end-start
        if period_func<period:
            if fr>max_calls:
                break
            time.sleep(period-period_func)
    return wrapper


Функция create_tuple выполнялась: 0.55 сек
